### PR TITLE
Maintainability, tooling, and community improvements

### PR DESCRIPTION
**Pull request by SampsonCrowley**
adds `flow`, `prettify`, and `pull-request` scripts to make pull-requests easier to keep consistent with codebase

### CODE REVIEW

**Comment by SampsonCrowley** [comment]
should the `.npmignore` file in `src/` be in the root directory?

**Comment by cbothner** [comment]
smh of course

**Comment by SampsonCrowley** [comment]
haha looks like you grabbed relevant common gitignore settings form the same place I did

**Comment by SampsonCrowley** [comment]
we can probably leave the runtime section out, since that mostly applies to ruby/rails and this isn't a framework or anything ran in realtime

**Comment by cbothner** [comment]
Makes sense 👍

**Comment by cbothner** [comment]
You're right: nothing needed in the changelog. I realized eslint was silently passing everything and I'm messing with the config...

**Comment by SampsonCrowley** [comment]
Sounds good. I'll leave it be for now

**Comment by SampsonCrowley** [comment]
Once you're done getting the settings where you want them I can help go through and fix the problems it wasn't catching

**Comment by cbothner** [comment]
Thanks for the offer; there weren't that many things to fix. (Now CodeClimate, on the other hand, might give me a hard time about the plugin I wanted....)

**Pull request merged**
